### ISSUE TITLE
Modal alignment changes if page has scrollbars

### ISSUE THREAD

**Issue by raddevon** [emalherbi/bootstrap-modal-stacked#1]
I believe this is caused by the padding Bootstrap adds to prevent shifting on a page with vertical scrollbars. The best solution would be for all modals past the first to copy the `padding-right` from the first.

Here are a couple of screenshots showing the problem. The first was taken on a page with scrollbars. The second was taken on a page without scrollbars.

![offset stack due to scrollbars](https://cloud.githubusercontent.com/assets/2027711/9014469/9198848e-3790-11e5-8e38-fd5c3461c1ec.png)
![stack on page without scrollbars](https://cloud.githubusercontent.com/assets/2027711/9014499/b259230e-3790-11e5-8e12-ce4223987253.png)

**Comment by raddevon** [comment]
Disregard this. It seems your script is not doing anything to handle my stacked modals. I put a couple of breakpoints into the script, and they never break when I open modals. I took the script out and the behavior is identical. Seems this is just the behavior of Bootstrap when opening multiple modals.

**Comment by emalherbi** [comment]
Hi @raddevon... 

Tks for contact.

If you want to see how the script works, see the page [bootstrap-modal-stacked](http://emalherbi.github.io/bootstrap-modal-stacked/). 

[]'s
